Add TagName support
itzg/restify pull request #2
Opened 2022-08-28 11:59 UTC by nxm

You can access the tagname by atom fields
`subset = FindSubnetByTagName(root, atom.Tbody)`

Or you can match it by string with lookup function

`atom.Lookup([]byte("tbody"))`

2022-08-28 13:48 UTC, itzg requested changes
Great addition!

2022-08-28 13:48 UTC, itzg commented on cmd/main.go
> +		subset = restify.FindSubnetByTagName(root, atom.Lookup([]byte(*byTagName)))
It should be named `FindSubsetByTagName` for consistency. README will also need to be tweaked.

2022-08-28 13:48 UTC, itzg commented on cmd/main.go
> +		subset = restify.FindSubnetByTagName(root, atom.Lookup([]byte(*byTagName)))
Please follow the pattern of the others where second arg should only be `*byTagName`. The atom details should be encapsulated inside the function.

2022-08-28 13:48 UTC, itzg commented on go.mod
> +module github.com/nxm/restify
Leftover from fork

2022-08-29 09:18 UTC, nxm commented
Thanks for CR ❤️

2022-08-29 12:07 UTC, itzg approved these changes
Thanks for the updates

2022-08-29 12:07 UTC, merged

2022-08-30 03:10 UTC, itzg commented
This is now released https://github.com/itzg/restify/releases/tag/1.6.0